'use strict';
const D=window.DASHBOARD, W=D.wells, names=Object.keys(W), $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=(v,d=0)=>Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const value=(v,d=1)=>v==null||v===''?'—':typeof v==='number'?fmt(v,d):esc(v);
const date=v=>v?String(v).slice(0,10):'—';
const sum=(arr,fn)=>arr.reduce((a,v)=>a+fn(v),0);
const kpi=(label,n,unit='',note='')=>`<div class="mini-kpi"><small>${label}</small><strong>${n} <span>${unit}</span></strong><span>${note}</span></div>`;
const table=(headers,rows,cls='')=>`<div class="table-scroll"><table class="${cls}"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
const tag=s=>`<span class="tag ${s==='완료'?'done':s.includes('진행')?'active':'pending'}">${esc(s)}</span>`;
const tabs=[['summary','Operations & plan'],['trajectory','3D trajectory'],['time','Time–depth'],['bha','BHA · all runs'],['parameters','Drilling parameters'],['issues','NPT & lessons'],['sources','Sources']];
let cleanup=()=>{},currentWell=null,currentTab='summary';
let runState={},sectionState={};
function overview(){
 const all=names.map(n=>W[n]);const progress=100*sum(all,w=>w.earnedDays)/sum(all,w=>w.planDays);const q=W['SHD-Q'];const recent=q.recentReports||[];const supplementTP=sum(all,w=>w.supplementNpt.TP);const recentRange=recent.length?`${recent[0].date}–${recent.at(-1).date}`:'—';
 $('#app').innerHTML=`<section class="intro"><div><p class="eyebrow">4 wells · 1 campaign · full lifecycle</p><h1>Beyond TD.<br>Through completion.</h1><p>시추부터 completion, well clean-up, BOP 회수까지.<br>계획 대비 완료 작업을 확인하는 Shwe Phase 4 운영 대시보드입니다.</p></div><aside class="snapshot"><p class="eyebrow">SHD-Q · DDR ${esc(D.cutoff)}</p><b>${esc(W['SHD-Q'].latestDayOperation)}</b><p>${esc(W['SHD-Q'].operation)}<br><br>다음날 06:00 현황: ${esc(W['SHD-Q'].lookaheadOperation)}<br><span class="muted">06:00 기록은 24시간 합계에서 제외</span></p></aside></section>
 <div class="kpi-row">${kpi('4-well weighted progress',fmt(progress,1),'%', '완료 작업 P50 가중 · 계산 지표')}${kpi('TP · Summary + latest DDR',fmt(sum(all,w=>w.npt.TP),2),'h',`기존 ${fmt(sum(all,w=>w.summaryNpt.TP),2)} + 추가 ${fmt(supplementTP,2)}h`)}${kpi('Unplanned · U',fmt(sum(all,w=>w.npt.U),2),'h','TP와 별도 분류')}${kpi('Trouble unplanned · TU',fmt(sum(all,w=>w.npt.TU),2),'h',`TP + TU = ${fmt(sum(all,w=>w.npt.TP+w.npt.TU),2)}h`)}</div>
 <div class="callout">최근 DDR ${recent.length}일(${recentRange}): <b>TP +${fmt(q.supplementNpt.TP,2)}h</b> · 책임 주체 미확정. GTV packer 회수 작업이 진행됐지만 upper completion은 미완료이므로 SHD-Q 진척도는 <b>${fmt(q.progress,1)}%</b> 유지. <a href="#well/SHD-Q/summary">일별 작업 이력 보기</a></div>
 <section class="section-block"><header class="section-head"><div><p class="eyebrow">Operation-weighted progress</p><h2>Four wells, different stages</h2></div><a href="#sources">진척도 계산 기준 ↗</a></header><div class="well-grid">${all.map(w=>`<a class="well-card" href="#well/${w.name}/summary" style="--accent:${w.color}"><div class="well-top"><div><span class="well-field">${w.field}</span><h3>${w.name}</h3></div><span class="card-status ${w.statusClass}">${w.name==='SHD-Q'?'Completion':'Suspended'}</span></div><strong class="progress-number">${fmt(w.progress,1)}<small>%</small></strong><div class="depth-track"><i style="width:${w.progress}%"></i></div><span class="note">완료 작업 ${fmt(w.earnedDays,1)} / ${fmt(w.planDays,1)} P50 days</span><p>${w.name==='SHD-Q'?'Lower completion 완료 · Upper completion 잔여':esc(w.operation)}</p><div class="well-metrics"><div><strong>${fmt(w.md,1)} m</strong><small>Current MD</small></div><div><strong>${fmt(w.npt.TP,2)} h</strong><small>TP NPT</small></div></div></a>`).join('')}</div><p class="note">TD 비율이 아닙니다. 완료된 단계만 P50 일수로 가중하며 진행 중 단계의 부분 기성은 포함하지 않습니다. 공식 기성률이 아닌 보수적 계산치입니다.</p></section>
 <article class="panel"><p class="eyebrow">Campaign time–depth</p><h2>4-well TD curve</h2><p class="note">동일한 달력 축 · 실적 MD / 모델 계획. Completion은 TD에서 깊이 변화 없이 시간이 증가합니다.</p><div id="timeChart"></div></article>
 <article class="panel"><p class="eyebrow">Side by side · installed casing</p><h2>Well schematic 비교</h2><p class="note">공통 0–4,000m MD 축. 케이싱 폭은 설명용이며 실제 직경 비례가 아닙니다. 편향 궤적은 상세 3D에서 확인하세요.</p><div class="schematic-grid">${all.map(schematic).join('')}</div></article>
 <section class="two-col"><article class="panel"><p class="eyebrow">NPT attribution</p><h2>Responsible party · TP / TU</h2>${partyBars(all)}<p class="note">책임 주체는 ${esc(D.nptSource)} 기준입니다. ${recentRange} 추가 TP ${fmt(q.supplementNpt.TP,2)}h는 미확정으로 분리했으며 Bluewhale 등에 임의 배분하지 않았습니다. WOW = 날씨 대기. U는 별도 집계합니다.</p></article><article class="panel"><p class="eyebrow">Summary + online DDR through ${esc(D.cutoff)}</p><h2>Well별 실제 시간</h2>${nptTable(all)}<div class="callout">SHD-Q TP: <b>${fmt(q.summaryNpt.TP,2)} + ${fmt(q.supplementNpt.TP,2)} = ${fmt(q.npt.TP,2)}h</b><br>Summary는 28 Sep까지, 이후는 DDR의 매일 00:00–24:00 online 기록만 합산했습니다.</div><p class="note">다음날 00:00–06:00 및 offline 병행 작업은 중복 제외합니다. 모든 시간은 0.25h 단위를 보존합니다.</p></article></section>`;
 setupTimeChart(names);
}
function schematic(w){
 const sy=d=>34+d/4000*285;let lines='';
 for(let d=0;d<=4000;d+=1000)lines+=`<line x1="30" y1="${sy(d)}" x2="230" y2="${sy(d)}" stroke="#203645"/><text x="0" y="${sy(d)-3}">${d}</text>`;
 const shoes=w.casingShoes||[];let previousLabel=0;
 const paths=shoes.map((s,i)=>{const off=40-i*7,y=sy(s.md),ly=Math.max(y,previousLabel+29);previousLabel=ly;return `<path d="M${87-off},${sy(0)} V${y} h5 M${87+off},${sy(0)} V${y} h-5" stroke="${w.color}" stroke-opacity="${Math.min(1,.4+i*.15)}" fill="none" stroke-width="2.5"/><path d="M${87+off},${y} L127,${ly}" stroke="${w.color}" stroke-opacity=".3"/><text x="130" y="${ly-3}">${esc(s.n)}</text><text x="130" y="${ly+10}">${fmt(s.md,1)}m</text><title>${esc(s.source)}</title>`}).join('');
 return `<div class="schematic-card" style="--c:${w.color}"><h3><a href="#well/${w.name}/trajectory" style="color:inherit">${w.name} ↗</a></h3><svg class="schematic" viewBox="0 0 235 358" role="img" aria-label="${w.name} installed casing depths">${lines}<line x1="87" y1="34" x2="87" y2="${sy(w.md)}" stroke="${w.color}" stroke-width="4"/>${paths}<circle cx="87" cy="${sy(w.md)}" r="4" fill="${w.color}"/><text x="45" y="345" fill="${w.color}">Current MD ${fmt(w.md,1)}m</text></svg><div class="schematic-note">${w.name==='SHD-Q'?'Lower completion 완료 / UC 진행':'Temporarily suspended'}<br>Model final hole TD: ${fmt(w.finalTd,1)}m<br>Current TVD: ${fmt(w.tvd,1)}m</div></div>`;
}
function nptTable(wells){return table(['Well','TP (h)','U (h)','TU (h)','TP+TU (h)'],wells.map(w=>`<tr><td><a href="#well/${w.name}/issues">${w.name}</a></td>${[w.npt.TP,w.npt.U,w.npt.TU,w.npt.TP+w.npt.TU].map(x=>`<td class="num">${fmt(x,2)}</td>`).join('')}</tr>`))}
function partyTotals(wells){const p={};wells.forEach(w=>Object.entries(w.parties).forEach(([name,t])=>{p[name]??={TP:0,TU:0,U:0};['TP','TU','U'].forEach(k=>p[name][k]+=t[k])}));return Object.entries(p).filter(([,t])=>t.TP+t.TU>0).sort((a,b)=>b[1].TP+b[1].TU-a[1].TP-a[1].TU)}
function partyBars(wells){const p=partyTotals(wells),max=p[0]?.[1].TP+p[0]?.[1].TU||1;return p.map(([name,t])=>`<div class="bar-row"><span>${esc(name)}${name==='WOW'?' · 날씨':''}</span><div class="bar-track"><i style="width:${100*(t.TP+t.TU)/max}%;background:${name.includes('미확정')?'var(--amber)':name==='WOW'?'var(--blue)':'var(--cyan)'}"></i></div><span class="num" title="TP ${fmt(t.TP,2)} / TU ${fmt(t.TU,2)}">${fmt(t.TP+t.TU,2)} h</span></div>`).join('')}
function detail(name,tab){const w=W[name];currentWell=name;currentTab=tabs.some(t=>t[0]===tab)?tab:'summary';
 $('#app').innerHTML=`<section class="detail-hero"><a class="back-link" href="#overview">‹ Campaign overview</a><div class="detail-title"><div><p class="eyebrow">${w.field} · ${w.report}</p><h1 style="color:${w.color}">${name}</h1><p>${esc(w.subtitle)}</p></div>${tag(name==='SHD-Q'?'진행 중 · Completion':'Suspended')}</div><div class="kpi-row">${kpi('Full-scope progress',fmt(w.progress,1),'%','P50-weighted completed operations')}${kpi('Current MD / TVD',fmt(w.md,1),'m',`TVD ${fmt(w.tvd,1)}m`)}${kpi('NPT · TP',fmt(w.npt.TP,2),'h',`U ${fmt(w.npt.U,2)}h · TU ${fmt(w.npt.TU,2)}h`)}${kpi('Model final hole TD',fmt(w.finalTd,1),'m','TD ≠ full operation completion')}</div></section><nav class="detail-tabs" aria-label="Well details">${tabs.map(([id,label])=>`<a class="tab-link ${currentTab===id?'active':''}" href="#well/${name}/${id}">${label}</a>`).join('')}</nav><div id="content"></div>`;
 if(currentTab==='summary')renderSummary(w);
 if(currentTab==='trajectory')renderTrajectory(w);
 if(currentTab==='time'){$('#content').innerHTML='<article class="panel"><h2>Time–depth curve</h2><div id="timeChart"></div></article>';setupTimeChart([name])}
 if(currentTab==='bha'||currentTab==='parameters')renderRuns(w,currentTab==='parameters');
 if(currentTab==='issues')renderIssues(w);
 if(currentTab==='sources')$('#content').innerHTML=sources(w);
}
function renderSummary(w){
 $('#content').innerHTML=`<div class="two-col"><article class="panel"><p class="eyebrow">Latest operation</p><h2>${esc(w.operation)}</h2><p>${esc(w.operationNote)}</p><p class="note">${esc(w.sources[0])} · ${w.ddrDate}</p>${w.name==='SHD-Q'?'<div class="callout">TD 도달 및 lower completion 완료. Upper completion / clean-up / final BOP recovery 잔여. Annular 정비는 진척률 증가로 계산하지 않습니다.</div>':''}<h3>잔여 계획</h3>${w.plan.filter(p=>p.status!=='완료'&&p.days>0).slice(0,5).map(p=>`<p class="note">${tag(p.status)} ${esc(p.operation)} · ${fmt(p.days,2)} P50 days</p>`).join('')}</article><article class="panel">${schematic(w)}</article></div>
 <article class="panel"><p class="eyebrow">Phase 4 Model_Updated</p><h2>전체 작업 계획과 진척</h2><p class="note">${fmt(w.earnedDays,2)} / ${fmt(w.planDays,2)} P50 days = ${fmt(w.progress,1)}%. 완료 단계의 가중치만 반영합니다. 모델 실제 날짜는 9월 10일 이후 DDR 단계 이력으로 보완했습니다.</p>${table(['단계 / 작업','상태','P50 days','Plan MD (m)','모델 예정 종료','모델 forecast 종료','근거'],w.plan.map(p=>`<tr><td>${esc(p.operation)}</td><td>${tag(p.status)}</td><td class="num">${fmt(p.days,2)}</td><td class="num">${value(p.md,1)}</td><td>${date(p.finish)}</td><td>${date(p.forecast)}</td><td class="muted">${esc(p.basis)}</td></tr>`))}<p class="note">예정/forecast는 모델 원문 값이며 현재 날짜 기준 재산정한 일정이 아닙니다. 0일/가중치 없는 작업은 진척도 분모에 포함하지 않습니다.</p></article>
 ${recentPanel(w)}
 <article class="panel"><h2>DDR 실제 작업 이력</h2><p class="note">Summary 이후 신규 일자는 DDR online 기록을 추가했습니다. 책임 주체 미확정 시간도 class별 실적 시간에 포함됩니다.</p>${table(['Operation','Start','Finish','P (h)','TP (h)','U (h)','TU (h)','Source'],w.operations.map(o=>`<tr><td>${esc(o.name)}${o.note?`<p class="note">${esc(o.note)}</p>`:''}</td><td>${date(o.start)}</td><td>${date(o.finish)}</td>${['P','TP','U','TU'].map(k=>`<td class="num">${value(o[k],2)}</td>`).join('')}<td class="source-path">${o.source?esc(o.source.split('/').at(-1)):'Summary!'+o.row}</td></tr>`))}</article>`;
}
function recentPanel(w){
 if(!w.recentReports?.length)return '';
 return `<article class="panel recent-ddr"><p class="eyebrow">Latest DDR · 24-hour online records</p><h2>최근 ${w.recentReports.length}일 작업 / 복구 이력</h2><p class="note">${esc(w.progressNote)}<br>현재 MD ${fmt(w.md,1)}m · TVD ${fmt(w.tvd,1)}m. 신규 drilling / survey / BHA tally는 없어 기존 자료를 유지합니다.</p>${table(['DDR date','작업 / 확인 결과','TP (h)','Source'],[...w.recentReports].reverse().map(r=>`<tr><td>${r.date}</td><td><b>${esc(r.title)}</b><p class="note">${esc(r.note)}</p></td><td class="num">${fmt(r.totals.TP,2)}</td><td class="source-path">${esc(r.source.split('/').at(-1))}</td></tr>`))}<div class="callout"><b>별도 다음날 현황 · ${esc(w.currentAsOf)}</b><br>${esc(w.lookaheadOperation)}. 이 6시간은 ${esc(D.cutoff)} 마감 누계에 포함하지 않습니다.</div><h3>다음 작업 · 최신 DDR 계획</h3>${w.nextSteps.map(([,title,note])=>`<details><summary>${esc(title)}</summary><p class="note">${esc(note)}</p></details>`).join('')}</article>`;
}
function setupTimeChart(scope){
 const box=$('#timeChart');let active=new Set(scope),showPlan=false,showForecast=true;
 box.innerHTML=`<div class="controls">${scope.map(n=>`<label><input type="checkbox" data-curve-well="${n}" checked>${n}</label>`).join('')}<label><input id="showForecast" type="checkbox" checked>Model actual + forecast</label><label><input id="showPlan" type="checkbox">Model P50 plan</label></div><div class="legend">${scope.map(n=>`<span style="--c:${W[n].color}">${n}</span>`).join('')}<span style="--c:#b2cbdc">실선: DDR actual</span><span class="dashed" style="--c:#b2cbdc">긴 점선: model forecast</span></div><div class="chart-scroll" id="tdPlot"></div><div class="chart-tip" id="tdTip">점에 마우스를 올리거나 터치하면 날짜·깊이·출처를 확인할 수 있습니다.</div><p class="note">Calendar date / MD(m). 실적은 각 DDR 첫 페이지 Current MD입니다. 공란인 초기 날짜는 제외합니다. 7일 초과 자료 공백은 짧은 점선이며 실제 시추 이력을 뜻하지 않습니다. Model curve는 행별 milestone이고 미래 일정은 모델 원문 값입니다.</p>`;
 function draw(){
  const series=[];
  [...active].forEach(n=>{const w=W[n];series.push({name:n,color:w.color,kind:'actual',points:w.actualCurve.map(p=>({date:p[0],md:p[1],label:`Current MD · ${p[2].split('/').at(-1)}`}))});
   for(const kind of ['forecast','plan']){if(kind==='plan'&&!showPlan||kind==='forecast'&&!showForecast)continue;let group=[],last=null;for(const p of w.plan){const t=kind==='forecast'?p.forecast:p.finish,md=kind==='forecast'?p.forecastMd:p.md;if(!t||typeof md!=='number')continue;if(last!==null&&p.row!==last+1){if(group.length)series.push({name:n,color:w.color,kind,points:group});group=[]}group.push({date:t,md,label:`Model row ${p.row} · ${p.operation}`});last=p.row}if(group.length)series.push({name:n,color:w.color,kind,points:group})}
  });
  const pts=series.flatMap(s=>s.points);if(!pts.length){$('#tdPlot').innerHTML='<p class="empty">표시할 well을 선택하세요.</p>';return}
  const ts=s=>Date.parse(s.slice(0,10)+'T00:00:00Z');const min=Math.min(...pts.map(p=>ts(p.date))),max=Math.max(...pts.map(p=>ts(p.date))),maxD=Math.ceil(Math.max(4000,...pts.map(p=>p.md))/500)*500;
  const width=1120,height=425,left=65,top=25,pw=1010,ph=340;const x=d=>left+(ts(d)-min)/Math.max(86400000,max-min)*pw,y=d=>top+d/maxD*ph;
  let svg=`<svg class="td-svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="Time depth plot"><text x="7" y="15">MD (m)</text>`;
  for(let d=0;d<=maxD;d+=500)svg+=`<line class="grid" x1="${left}" y1="${y(d)}" x2="${left+pw}" y2="${y(d)}"/><text x="${left-10}" y="${y(d)+4}" text-anchor="end">${d}</text>`;
  for(let i=0;i<=8;i++){const t=min+(max-min)*i/8,xx=left+pw*i/8,label=new Date(t).toISOString().slice(0,10);svg+=`<line class="grid" x1="${xx}" y1="${top}" x2="${xx}" y2="${top+ph}"/><text x="${xx}" y="${top+ph+26}" text-anchor="middle">${label}</text>`}
  for(const s of [...series].sort((a,b)=>(a.kind==='actual')-(b.kind==='actual'))){s.points.forEach((p,i)=>{const prev=s.points[i-1];if(prev){const gap=ts(p.date)-ts(prev.date)>7*86400000;svg+=`<line x1="${x(prev.date)}" y1="${y(prev.md)}" x2="${x(p.date)}" y2="${y(p.md)}" stroke="${s.color}" stroke-width="${s.kind==='actual'?2.5:1.7}" stroke-opacity="${s.kind==='actual'?1:.6}" stroke-dasharray="${s.kind==='forecast'?'9 5':s.kind==='plan'?'2 5':gap?'3 4':'none'}"/>`}const tip=`${s.name} · ${s.kind} · ${date(p.date)} · ${fmt(p.md,1)}m · ${p.label}`;svg+=`<circle cx="${x(p.date)}" cy="${y(p.md)}" r="${s.kind==='actual'?3:2}" fill="${s.color}" opacity="${s.kind==='actual'?1:.6}" tabindex="0" data-tip="${esc(tip)}"><title>${esc(tip)}</title></circle>`})}
  const cut=x(D.cutoff);if(cut>=left&&cut<=left+pw)svg+=`<line x1="${cut}" y1="${top}" x2="${cut}" y2="${top+ph}" stroke="#ffb95a" stroke-dasharray="5 5"/><text x="${Math.min(cut+6,960)}" y="16" style="fill:#ffb95a">DDR cut-off ${esc(D.cutoff)}</text>`;
  $('#tdPlot').innerHTML=svg+'</svg>';box.querySelectorAll('[data-tip]').forEach(el=>['pointerenter','focus','click'].forEach(ev=>el.addEventListener(ev,()=>$('#tdTip').textContent=el.dataset.tip)));
 }
 box.querySelectorAll('[data-curve-well]').forEach(e=>e.onchange=()=>{e.checked?active.add(e.dataset.curveWell):active.delete(e.dataset.curveWell);draw()});$('#showPlan').onchange=e=>{showPlan=e.target.checked;draw()};$('#showForecast').onchange=e=>{showForecast=e.target.checked;draw()};draw();
}
function renderTrajectory(w){
 if(!w.surveys.length){$('#content').innerHTML='<p class="empty">Survey 자료를 확인할 수 없습니다.</p>';return}
 $('#content').innerHTML=`<article class="panel"><p class="eyebrow">Survey-derived spatial view</p><h2>3D trajectory · ${w.name}</h2><div class="controls"><label>Wellbore <select id="surveySelect">${w.surveys.map((s,i)=>`<option value="${i}">${esc(s.name)}</option>`).join('')}</select></label><button class="btn active" data-view="3d">3D</button><button class="btn" data-view="section">Vertical section</button><button class="btn" data-view="plan">Plan · E/N</button><label>수평 확대 <select id="exaggeration"><option value="1">1× · 실제 축척</option><option value="10">10×</option><option value="50">50×</option><option value="100">100×</option></select></label><button class="btn" id="resetView">Reset</button></div><canvas class="trajectory-canvas" id="trajectory" aria-label="Survey-based 3D well trajectory. Drag to rotate; use controls and station table for data." role="img"></canvas><div class="controls"><label>회전 <input type="range" id="yaw" min="-180" max="180" value="-25"></label><label>기울기 <input type="range" id="tilt" min="-70" max="70" value="20"></label><label>Survey station <input type="range" id="station" min="0" value="0"></label></div><div class="trajectory-stats" id="stationInfo"></div><div id="surveyNote"></div><details><summary>전체 survey station 확인</summary><div id="surveyTable"></div></details></article>`;
 let idx=0,mode='3d',yaw=45,tilt=20,ex=1,selected=0,pointer=null;
 const homeYaw=()=>{const p=w.surveys[idx].stations.at(-1);return Math.atan2(-p[4],p[5])*180/Math.PI};
 const canvas=$('#trajectory'),ctx=canvas.getContext('2d');
 function setup(){const s=w.surveys[idx];selected=s.stations.length-1;$('#station').max=selected;$('#station').value=selected;$('#surveyNote').innerHTML=`<p class="note">실제 좌표: E/W, N/S, TVD(m). 기본 축척 1:1. 드래그로 회전하며, 0m는 survey datum 기준입니다. ${s.referenceExtension?'원점~첫 tie-on 구간은 측정값이 아닌 점선 참조선입니다.':'원본에 포함된 0m/tie-on 좌표를 그대로 표시합니다.'} 마지막 survey 이후의 TD 구간은 추정하지 않습니다.</p><p class="source-path">${esc(s.source)}</p>`;$('#surveyTable').innerHTML=table(['MD (m)','Inc (°)','Azi (°)','TVD (m)','North (m)','East (m)'],s.stations.map(p=>`<tr>${p.map(v=>`<td class="num">${fmt(v,2)}</td>`).join('')}</tr>`));draw()}
 function draw(){
  const s=w.surveys[idx],stations=s.stations;const dpr=window.devicePixelRatio||1,b=canvas.getBoundingClientRect();canvas.width=Math.round(b.width*dpr);canvas.height=Math.round(b.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);const width=b.width,height=b.height;ctx.clearRect(0,0,width,height);
  const depth=Math.ceil(Math.max(w.tvd,...stations.map(p=>p[3]))/500)*500;const radius=Math.max(100,Math.ceil(Math.max(...stations.map(p=>Math.hypot(p[4],p[5])))/500)*500);const ang=yaw*Math.PI/180,t=tilt*Math.PI/180;
  const last=stations.at(-1),az=Math.atan2(last[5],last[4]);
  function proj(E,N,Z){E*=ex;N*=ex;if(mode==='plan')return [E,-N];if(mode==='section')return [E*Math.sin(az)+N*Math.cos(az),Z];const u=E*Math.cos(ang)-N*Math.sin(ang),v=E*Math.sin(ang)+N*Math.cos(ang);return [u,Z*Math.cos(t)-v*Math.sin(t)]}
  const coords=stations.map(p=>proj(p[5],p[4],p[3]));const bounds=[...coords,proj(0,0,0),proj(0,0,depth)];if(mode==='3d')bounds.push(proj(radius,0,0),proj(0,radius,0));
  let minX=Math.min(...bounds.map(p=>p[0])),maxX=Math.max(...bounds.map(p=>p[0])),minY=Math.min(...bounds.map(p=>p[1])),maxY=Math.max(...bounds.map(p=>p[1]));
  const scale=Math.min((width-140)/Math.max(100,maxX-minX),(height-100)/Math.max(100,maxY-minY));
  const xy=p=>[(width-(maxX-minX)*scale)/2+(p[0]-minX)*scale,50+(p[1]-minY)*scale];
  function line(a,b,color,dash=[],lw=1){ctx.beginPath();ctx.setLineDash(dash);ctx.lineWidth=lw;ctx.strokeStyle=color;ctx.moveTo(...xy(a));ctx.lineTo(...xy(b));ctx.stroke();ctx.setLineDash([])}
  function label(p,text,color='#8eabbe',dx=8,dy=0){const q=xy(p);ctx.fillStyle=color;ctx.font='11px Consolas, monospace';ctx.fillText(text,q[0]+dx,q[1]+dy)}
  if(mode!=='plan'){line(proj(0,0,0),proj(0,0,depth),'#4d6c80',[4,5]);for(let z=0;z<=depth;z+=500)label(proj(0,0,z),`${z}m TVD`,'#7793a6',-85,4)}
  line(proj(0,0,0),proj(radius,0,0),'#46687e');line(proj(0,0,0),proj(0,radius,0),'#46687e');label(proj(radius,0,0),`E +${radius}m`);label(proj(0,radius,0),`N +${radius}m`,undefined,4,-10);label(proj(0,0,0),'0m datum','#ffb95a',8,-13);
  if(s.referenceExtension)line(proj(0,0,0),coords[0],'#7b98ab',[5,5],2);
  for(let i=1;i<coords.length;i++)line(coords[i-1],coords[i],w.color,[],3);
  coords.forEach((p,i)=>{if(i%3===0||i===selected){ctx.beginPath();ctx.arc(...xy(p),i===selected?5:2.1,0,Math.PI*2);ctx.fillStyle=i===selected?'#fff':w.color;ctx.fill()}});
  const p=stations[selected];label(coords[selected],`MD ${fmt(p[0],1)}m`,w.color,10,0);
  ctx.fillStyle=ex===1?'#91b3c9':'#ffb95a';ctx.font='12px Consolas, monospace';ctx.fillText(`${mode.toUpperCase()} · horizontal ${ex}× · ${stations.length} stations`,18,24);
  const scaleUnit=mode==='plan'?ex:1;const unit=100/scale/scaleUnit;ctx.strokeStyle='#708fa3';ctx.beginPath();ctx.moveTo(18,height-22);ctx.lineTo(118,height-22);ctx.stroke();ctx.fillText(`${fmt(unit,unit<10?1:0)}m projected scale${ex>1&&mode!=='plan'?' · before H exaggeration':''}`,18,height-32);
  $('#stationInfo').innerHTML=[`MD ${fmt(p[0],2)}m`,`TVD ${fmt(p[3],2)}m`,`N ${fmt(p[4],2)}m`,`E ${fmt(p[5],2)}m`,`Inc ${fmt(p[1],2)}°`,`Azi ${fmt(p[2],2)}°`,`Departure ${fmt(Math.hypot(p[4],p[5]),2)}m`].map(t=>`<span>${t}</span>`).join('');
 }
 $('#surveySelect').onchange=e=>{idx=+e.target.value;setup()};$('#exaggeration').onchange=e=>{ex=+e.target.value;draw()};$('#station').oninput=e=>{selected=+e.target.value;draw()};$('#yaw').oninput=e=>{yaw=+e.target.value;draw()};$('#tilt').oninput=e=>{tilt=+e.target.value;draw()};
 document.querySelectorAll('[data-view]').forEach(e=>e.onclick=()=>{mode=e.dataset.view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===e));draw()});$('#resetView').onclick=()=>{yaw=-25;tilt=20;ex=1;$('#yaw').value=yaw;$('#tilt').value=tilt;$('#exaggeration').value=1;draw()};
 canvas.onpointerdown=e=>{pointer=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!pointer||mode!=='3d')return;yaw=Math.max(-180,Math.min(180,yaw+(e.clientX-pointer[0])*.5));tilt=Math.max(-70,Math.min(70,tilt+(e.clientY-pointer[1])*.4));pointer=[e.clientX,e.clientY];$('#yaw').value=yaw;$('#tilt').value=tilt;draw()};canvas.onpointerup=()=>pointer=null;canvas.onpointercancel=()=>pointer=null;
 yaw=homeYaw();$('#yaw').value=yaw;
 $('#resetView').onclick=()=>{yaw=homeYaw();tilt=20;ex=1;$('#yaw').value=yaw;$('#tilt').value=tilt;$('#exaggeration').value=1;draw()};
 const ro=new ResizeObserver(()=>draw());ro.observe(canvas);cleanup=()=>ro.disconnect();setup();
}
function renderRuns(w,paramsOnly){
 const sections=[...new Set(w.runs.map(r=>r.sectionGroup))];let section=sectionState[w.name]||'all';let run=runState[w.name]||w.runs.at(-1).number;
 $('#content').innerHTML=`<article class="panel"><p class="eyebrow">Complete document register</p><h2>${paramsOnly?'Section & BHA drilling parameters':'BHA register · Run100 onwards'}</h2><p class="note">${w.runs.filter(r=>r.sources.length).length}개 Run 문서 / ${w.runs.filter(r=>r.parameters.length).length}개 Run parameter. Run 번호는 순번이며 자료 존재와 실제 작업 완료는 구분합니다.</p><div class="controls"><label>Section <select id="sectionSelect"><option value="all">전체 section</option>${sections.map(s=>`<option ${section===s?'selected':''} value="${esc(s)}">${esc(s)}</option>`).join('')}</select></label><button class="btn" id="allSectionParameters">선택 section 전체 parameter</button></div><div class="run-layout"><aside class="run-menu" id="runMenu"></aside><div id="runContent"></div></div></article>`;
 function paint(){const runs=w.runs.filter(r=>section==='all'||r.sectionGroup===section);if(!runs.some(r=>r.number===run))run=runs[0]?.number;runState[w.name]=run;sectionState[w.name]=section;
  $('#runMenu').innerHTML=runs.map(r=>`<button class="run-item ${r.number===run?'active':''}" data-run="${r.number}"><b>Run${r.number}</b><small>${esc(r.section)}</small><small>${esc(r.status)} · ${r.parameters.length} parameter rows</small></button>`).join('');
  $('#runMenu').querySelectorAll('[data-run]').forEach(e=>e.onclick=()=>{run=+e.dataset.run;paint()});
  const r=runs.find(r=>r.number===run);if(!r){$('#runContent').innerHTML='<p class="empty">해당 section 자료가 없습니다.</p>';return}
  $('#runContent').innerHTML=`<div class="run-heading"><div><h2>Run${r.number}</h2><p>${esc(r.section)}</p></div>${tag(r.status)}</div>${r.depthRange?`<p class="note">Parameter 기록 MD ${fmt(r.depthRange[0],1)}–${fmt(r.depthRange[1],1)}m · drillout / ream / RIH 포함 가능</p>`:''}${!paramsOnly?bhaView(r):''}<h3>Drilling parameters · Run${r.number}</h3><div id="paramContent"></div>`;
  parameters($('#paramContent'),[r]);
 }
 $('#sectionSelect').onchange=e=>{section=e.target.value;paint()};$('#allSectionParameters').onclick=()=>{const runs=w.runs.filter(r=>section==='all'||r.sectionGroup===section);$('#runContent').innerHTML=`<h2>${section==='all'?'전체 section':esc(section)}</h2><p class="note">${runs.map(r=>'Run'+r.number).join(' · ')} 통합. 다른 section/BHA 수치를 개별 Run에 대입하지 않습니다.</p><div id="paramContent"></div>`;parameters($('#paramContent'),runs);$('#runMenu').querySelectorAll('.active').forEach(e=>e.classList.remove('active'))};paint();
}
function bhaView(r){
 if(!r.sources.length)return '<div class="callout">이 Run의 BHA 문서를 제공 자료에서 찾지 못했습니다. 사용 여부·구성은 확인이 필요합니다.</div>';
 return `${r.status.includes('Draft')?'<div class="callout">Draft tally입니다. 실제 사용을 확정한 기록으로 표시하지 않습니다.</div>':''}${r.components.length?`<p class="note">Bit → uphole 순서. Drill pipe까지 포함된 tally는 drillstring 전체이며 총 길이를 BHA 길이로 오인하지 마세요. 구조화된 표는 PDF 자동 추출이므로 원문 tally와 대조 가능합니다.</p><div class="component-grid">${r.components.map(c=>`<div class="component"><b>#${c.item}</b>${esc(c.description)}<small>${fmt(c.length,2)}m · cum ${fmt(c.cumulative,2)}m</small></div>`).join('')}</div>`:'<p class="note">Checklist/space-out 형식: 아래 원문 추출표에서 구성과 치수를 확인하세요.</p>'}${r.tallies.map(t=>`<details><summary>전체 BHA / bit tally · ${esc(t.source)}</summary><pre class="tally">${esc(t.text)}</pre></details>`).join('')}<p class="source-path">${r.sources.map(esc).join('<br>')}</p>`;
}
const paramMetrics=[['rop','ROP','m/h'],['rpm','Surface RPM','rpm'],['wob','WOB','klbf'],['flow','Flow','gpm'],['spp','On-bottom SPP','psi'],['ecd','ECD','ppg']];
function parameters(target,runs){
 const all=runs.flatMap(r=>r.parameters.map(p=>({...p,run:r.number,section:r.section})));if(!all.length){target.innerHTML='<p class="empty">이 Run의 drilling parameter 원본이 제공되지 않았거나 drilling 작업이 아닙니다. 다른 Run의 값으로 대체하지 않았습니다.</p>';return}
 target.innerHTML=`<div class="controls"><label><input id="drillOnly" type="checkbox" checked>양의 footage + bit time 행만</label><label>Metric <select id="paramMetric">${paramMetrics.map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</select></label></div><div class="param-kpis" id="paramKpis"></div><div id="paramChart"></div><p class="note">Min / median / max는 숫자로 기록된 값만 계산합니다. “5–80”, “20/35” 같은 문자열 범위는 원문표에 보존하고 통계에서 제외합니다. Parameter는 기록값이며 운전 권장 범위가 아닙니다.</p><div id="paramTable"></div><p class="source-path">${runs.flatMap(r=>r.parameterSources).map(s=>`${esc(s.source)} · ${esc(s.sheet)} · ${s.records} rows`).join('<br>')}</p>`;
 function draw(){const records=all.filter(p=>!$('#drillOnly').checked||p.toMd>p.fromMd&&typeof p.hours==='number'&&p.hours>0);
  $('#paramKpis').innerHTML=paramMetrics.map(([id,label,unit])=>{const nums=records.map(p=>p[id]).filter(v=>typeof v==='number').sort((a,b)=>a-b),n=nums.length,med=n?(nums[Math.floor((n-1)/2)]+nums[Math.ceil((n-1)/2)])/2:null;return kpi(label,n?fmt(med,1):'—',unit,n?`${fmt(nums[0],1)} / ${fmt(med,1)} / ${fmt(nums.at(-1),1)} · n=${n}, 제외 ${records.length-n}`:'숫자 값 없음')}).join('');
  const id=$('#paramMetric').value,metric=paramMetrics.find(m=>m[0]===id),valid=records.filter(p=>typeof p[id]==='number');
  if(valid.length){const xmin=Math.min(...valid.map(p=>p.toMd)),xmax=Math.max(...valid.map(p=>p.toMd)),ymin=Math.min(0,...valid.map(p=>p[id])),ymax=Math.max(...valid.map(p=>p[id]));$('#paramChart').innerHTML=`<p class="note">${metric[1]} vs MD · 숫자 기록만 · 점에 마우스를 올리면 Run/깊이/값 확인</p><svg viewBox="0 0 860 160" role="img" aria-label="${metric[1]} by depth"><path d="M50 15 V125 H830" stroke="#38546a" fill="none"/>${valid.map(p=>`<circle cx="${50+(p.toMd-xmin)/Math.max(1,xmax-xmin)*780}" cy="${125-(p[id]-ymin)/Math.max(1,ymax-ymin)*100}" r="3" fill="${W[currentWell].color}" opacity=".75"><title>Run${p.run} · ${fmt(p.toMd,1)}m · ${p[id]} ${metric[2]}</title></circle>`).join('')}<text x="50" y="148" fill="#94aabc" font-size="11">${fmt(xmin)}m MD</text><text x="750" y="148" fill="#94aabc" font-size="11">${fmt(xmax)}m MD</text><text x="5" y="28" fill="#94aabc" font-size="11">${fmt(ymax)}</text></svg>`}else $('#paramChart').innerHTML='<p class="note">선택 metric에 숫자 데이터가 없습니다.</p>';
  $('#paramTable').innerHTML=table(['Run','MD from → to (m)','Bit h',...paramMetrics.map(([,label,unit])=>`${label} (${unit})`),'Mode / remarks','Source'],records.map(p=>`<tr><td>Run${p.run}</td><td class="num">${fmt(p.fromMd,1)} → ${fmt(p.toMd,1)}</td><td class="num">${value(p.hours,2)}</td>${paramMetrics.map(([id])=>`<td class="num">${value(p[id],2)}</td>`).join('')}<td>${esc(p.mode)}${p.note?`<p class="note">${esc(p.note)}</p>`:''}</td><td><details><summary>Row ${p.row}</summary>${esc(p.source)}<br>${esc(p.sheet)}</details></td></tr>`),'param-table');
 }$('#drillOnly').onchange=draw;$('#paramMetric').onchange=draw;draw();
}
function renderIssues(w){
 $('#content').innerHTML=`<div class="two-col"><article class="panel"><h2>NPT actual hours</h2>${nptTable([w])}<p class="note">TP+U+TU = ${fmt(w.npt.TP+w.npt.U+w.npt.TU,2)}h. 원본의 분류를 보존하며 U 전체를 업체 귀책 NPT로 취급하지 않습니다.</p>${w.supplementNpt.TP?`<div class="callout">TP ${fmt(w.summaryNpt.TP,2)}h (Summary) + ${fmt(w.supplementNpt.TP,2)}h (최신 DDR) = ${fmt(w.npt.TP,2)}h.<br>추가분의 class TP는 확인됐지만 책임 주체는 미확정입니다.</div>`:''}${table(['Responsible party','TP (h)','TU (h)'],partyTotals([w]).map(([name,t])=>`<tr><td>${esc(name)}${name==='WOW'?' (weather)':''}</td><td class="num">${fmt(t.TP,2)}</td><td class="num">${fmt(t.TU,2)}</td></tr>`))}</article><article class="panel"><h2>Source & interpretation</h2><p>${esc(D.nptSource)}</p><p class="note">Summary 이벤트는 ${w.name} 시트의 class / Responsible Party / NPT Event Name으로 묶었습니다. 이후 DDR 추가분은 별도 날짜별 그룹이며 원본 파일·페이지·시간대를 표시합니다.</p><p class="note">시간 합계에는 매일 00:00–24:00 online 기록만 사용합니다. 다음날 00:00–06:00, offline 병행 작업과 HSE의 T-Times는 합산하지 않습니다. 0.25h 단위를 보존합니다.</p><div class="callout">“책임 주체”는 DDR 분류입니다. 원인·조치·lesson이 확정되어 있지 않은 경우 작업 설명만으로 과실이나 close-out을 단정하지 않습니다.</div></article></div><article class="panel"><h2>NPT event register</h2><div class="controls"><label>Class <select id="eventClass"><option value="all">TP + U + TU</option><option>TP</option><option>U</option><option>TU</option></select></label><label>Party <select id="eventParty"><option value="all">전체</option>${Object.keys(w.parties).map(p=>`<option>${esc(p)}</option>`).join('')}</select></label><input type="search" id="eventSearch" placeholder="원인 / 장비 / 작업 검색" aria-label="Search NPT events"></div><div id="eventList"></div></article><article class="panel"><h2>Engineering follow-up / lesson candidates</h2><p class="note">DDR 검토에 따른 대응·재발 방지 검토 항목입니다. 공식 RCA나 확정 lesson learned가 아니며 실제 시간은 위 원본 register를 따릅니다.</p>${w.issues.map(i=>`<details><summary>${esc(i.title)}</summary><p>${esc(i.desc)}</p><div class="issue-columns"><div><small class="muted">원인 검토 / source interpretation</small><p>${esc(i.cause)}</p><small class="muted">대응 검토</small><p>${esc(i.response)}</p></div><div><small class="muted">Lesson candidate · 검증 필요</small><p>${esc(i.lesson)}</p></div></div></details>`).join('')}</article>`;
 function list(){const cls=$('#eventClass').value,party=$('#eventParty').value,q=$('#eventSearch').value.toLowerCase();const ev=w.events.filter(e=>(cls==='all'||e.category===cls)&&(party==='all'||e.party===party)&&(!q||JSON.stringify(e).toLowerCase().includes(q)));$('#eventList').innerHTML=`<p class="note">${ev.length} event groups · ${fmt(sum(ev,e=>e.hours),2)}h</p>`+ev.map(e=>`<details><summary><b>${fmt(e.hours,2)}h</b> · ${e.category} · ${esc(e.party)} · ${date(e.start)} — ${date(e.end)} <span class="muted">/ Event ${esc(e.id)}</span></summary>${e.records.map(r=>`<div class="event-record"><b>${date(r.date)} · ${fmt(r.hours,2)}h · Phase ${esc(r.phase)} · ${r.source?`${esc(r.start)}–${esc(r.end)}`:w.name+'!'+r.row}</b>${r.source?`<p class="source-path">${esc(r.source.split('/').at(-1))} · page ${r.page}</p>`:''}${r.causeCode?`<span class="tag">Cause ${esc(r.causeCode)}</span>`:''}<p>${esc(r.description)}</p></div>`).join('')}</details>`).join('')}
 ['eventClass','eventParty'].forEach(id=>$('#'+id).onchange=list);$('#eventSearch').oninput=list;list();
}
function sources(w){return `<article class="panel"><p class="eyebrow">Data lineage & limitations</p><h2>데이터 근거 / 계산 기준</h2><p class="source-path">${esc(D.modelSource)}<br>${esc(D.nptSource)}<br>DDR 24h cutoff: ${D.cutoff} · Summary cutoff: ${D.summaryCutoff} · Build: ${D.version}</p><ol class="source-notes">${D.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ol>${w?`<h3>${w.name} source register</h3><p class="note">이 well의 최신 DDR: ${w.ddrCutoff}</p>${table(['Type','Source'],[['DDR',w.sources[0]],...w.recentReports.map(r=>['DDR online supplement',r.source]),...w.surveys.map(s=>['Survey',s.source]),...w.runs.flatMap(r=>[...r.sources.map(s=>[`BHA Run${r.number}`,s]),...r.parameterSources.map(s=>[`Parameter Run${r.number}`,s.source+' · '+s.sheet])])].map(([type,src])=>`<tr><td>${esc(type)}</td><td class="source-path">${esc(src)}</td></tr>`))}`:''}</article>`}
function route(){cleanup();cleanup=()=>{};const m=location.hash.match(/^#well\/([^/]+)(?:\/([^/]+))?/);document.querySelectorAll('.topnav a').forEach(a=>a.classList.toggle('is-active',m?a.hash.includes('/'+m[1]+'/'):a.hash==='#overview'));if(m&&W[m[1]])detail(m[1],m[2]||'summary');else if(location.hash==='#sources')$('#app').innerHTML=sources();else{currentWell=null;overview()}window.scrollTo(0,0)}
window.addEventListener('hashchange',route);route();
